name: PaperRenameLorePlugin
version: 1.0
main: com.yourdomain.paperrenameloreplugin.PaperRenameLorePlugin
api-version: 1.20

commands:
  rename:
    description: Renames the item in your hand.
    usage: /rename <name>
  lore:
    description: Sets custom lore for the item in your hand.
    usage: /lore <lore>
