name: Build Paper Minecraft Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin-jar
        path: target/*.jar
